### ISSUE TITLE
Add a package.json

### ISSUE THREAD

**Issue by louicoder** [louiCoder/Node-WebScrapper#11]
Add a package.json to the project. This can be automated using a command `npm init -y` for defaults which you will edit in the created package.json file and replace the following keys
- **url** ( this should be the url of the git repository, get it from the project repo)
- **name**, this should `Node webscrapper`
- **description** , this should be `A web scrapper built on NodeJS for data analytics`

Run `npm install <package name> --save` so that the following packages are added to the package.json file
- [x] request
- [x] cheerio
- [x] apify
- [x] puppeteer

You can find more about setting up a package.json file here >> [Link to resource](https://medium.com/beginners-guide-to-mobile-web-development/why-package-json-npm-basics-cab3e8cd150)

**_Make sure the above checklist is complete_**

**Comment by Anekenonso** [comment]
package.json doesn't recognise "Node webscrapper". so "node-webscrapper" will be used

**Comment by louicoder** [comment]
> package.json doesn't recognise "Node webscrapper". so "node-webscrapper" will be used

@Anekenonso Thx for that observation. That's totally fine. I know for sure that you cannot have spaces in JavaScript object keys

**Comment by Anekenonso** [comment]
it's done!.
