### ISSUE TITLE
Create a cron-job

### ISSUE THREAD

**Issue by louicoder** [louiCoder/Node-WebScrapper#17]
Create a cron-job in a new file called **`cronJob.js`**. In this file set up a cron-job console log any output/string every after a number of seconds you have set. For more on how to get started on cron-jobs in NodeJS click   **[NodeJS cron-jobs](https://scotch.io/tutorials/nodejs-cron-jobs-by-examples)**

Make sure to run the cron-job in **`server.js`** file and not from your file.

**Comment by Anekenonso** [comment]
> In this file set up a cron-job console log any output/string every after a number of seconds you have set

can you elaborate more on this? the cronjob will output what exactly?
